// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _05.Entity_Relations_FootballBettingDatabase.Data;

#nullable disable

namespace _05.Entity_Relations_FootballBettingDatabase.Migrations
{
    [DbContext(typeof(FootballBettingContext))]
    partial class FootballBettingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Bet", b =>
                {
                    b.Property<int>("BetId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2)
                        .HasColumnType("DECIMAL(2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Prediction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BetId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamBetGoals")
                        .HasColumnType("int");

                    b.Property<decimal>("AwayTeamBetRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2)
                        .HasColumnType("DECIMAL(2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("DATETIME2");

                    b.Property<decimal>("DrawBetRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2)
                        .HasColumnType("DECIMAL(2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("HomeTeamBetGoals")
                        .HasColumnType("int");

                    b.Property<decimal>("HomeTeamBetRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2)
                        .HasColumnType("DECIMAL(2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInjured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("SquadNumber")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.PlayerStatistic", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("ScoredGoals")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("PlayersStatistics");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PositionId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<decimal>("Budget")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2)
                        .HasColumnType("DECIMAL(2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrimaryKitColorId")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryKitColorId")
                        .HasColumnType("int");

                    b.Property<int>("TownId")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.HasIndex("PrimaryKitColorId");

                    b.HasIndex("SecondaryKitColorId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Town", b =>
                {
                    b.Property<int>("TownId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TownId");

                    b.ToTable("Towns");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2)
                        .HasColumnType("DECIMAL(2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Bet", b =>
                {
                    b.HasOne("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Game", "Game")
                        .WithMany("Bets")
                        .HasForeignKey("BetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_05.Entity_Relations_FootballBettingDatabase.Data.Models.User", "User")
                        .WithMany("Bets")
                        .HasForeignKey("BetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Game", b =>
                {
                    b.HasOne("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Team", "AwayTeam")
                        .WithMany("AwayGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Team", "HomeTeam")
                        .WithMany("HomeGames")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Player", b =>
                {
                    b.HasOne("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Position", "Position")
                        .WithMany("Players")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.PlayerStatistic", b =>
                {
                    b.HasOne("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Game", "Game")
                        .WithMany("PlayersStatistics")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Player", "Player")
                        .WithMany("PlayersStatistics")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Team", b =>
                {
                    b.HasOne("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Color", "PrimaryKitColor")
                        .WithMany("PrimaryKitColorTeams")
                        .HasForeignKey("PrimaryKitColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Color", "SecondaryKitColor")
                        .WithMany("SecondaryKitColorTeams")
                        .HasForeignKey("SecondaryKitColorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Town", "Town")
                        .WithMany("Teams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryKitColor");

                    b.Navigation("SecondaryKitColor");

                    b.Navigation("Town");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Town", b =>
                {
                    b.HasOne("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Country", "Country")
                        .WithMany("Towns")
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Color", b =>
                {
                    b.Navigation("PrimaryKitColorTeams");

                    b.Navigation("SecondaryKitColorTeams");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Country", b =>
                {
                    b.Navigation("Towns");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Game", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("PlayersStatistics");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Player", b =>
                {
                    b.Navigation("PlayersStatistics");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Position", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Team", b =>
                {
                    b.Navigation("AwayGames");

                    b.Navigation("HomeGames");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.Town", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("_05.Entity_Relations_FootballBettingDatabase.Data.Models.User", b =>
                {
                    b.Navigation("Bets");
                });
#pragma warning restore 612, 618
        }
    }
}
